### ISSUE TITLE
imx-Add-MYiR-Tech-MYS-6ULX-support.patch

### ISSUE THREAD

**Issue by hyyoxhk** [linumiz/meta-mainline-bsp#1]
u-boot master had accepting your patch, so, Your u-boot recipe doesn't need to do_ patch

**Comment by parthitce** [comment]
@hyyoxhk Yes both u-boot and Linux Kernel patches are accepted in mainline now. We will adapt the recipe to point to mainline without patching or please submit PR.

**Comment by parthitce** [comment]
@hyyoxhk Both Kernel and U-boot is now pointing to mainline latest. Also now the layer can produce ubifs rootfs.
